version: '3.8'

services:
  postgres:
    image: postgres:17.0-alpine
    environment:
      - POSTGRES_PASSWORD=postgres_secret
      - POSTGRES_USER=root
      - POSTGRES_DB=expence
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgres/data

  minio:
    image: minio/minio:RELEASE.2024-10-02T17-50-41Z
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=minio_secret
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

volumes:
  pg_data:
  minio_data:
