name: ClientDevelop

on:
  push:
    branches:
      - "dev"
    paths:
      - "client/**"
  pull_request:
    branches:
      - "dev"
    paths:
      - "client/**"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js and cache dependencies
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: client/package-lock.json

      - name: Install dependencies
        working-directory: client
        run: |
          rm -rf node_modules package-lock.json
          npm install

      - name: Check code formatting with Prettier
        working-directory: client
        run: npx prettier --check .

      - name: Lint the client project
        working-directory: client
        run: npm run lint

      - name: Build the client project (if build script exists)
        working-directory: client
        run: npm run build --if-present
